exporter = "otlp"
processor = "batch"

[exporters.otlp]
host = "otel-collector.open-telemetry"
port = 4317

[processors.batch]
max_queue_size = 2048
schedule_delay_millis = 5000
max_export_batch_size = 512

[service]
name = "your-frontend-servicee-name"